---
# MEMORY POOL
# 'capacity' affects hugepage memory usage; (2^q-1) is optimal.
# 'cachesize' cannot exceed 512; (capacity % cachesize == 0) is optimal.
# 'dataroomsize' should be greater than MTU.
# Each NUMA socket has its own mempool with the given name.
mempool:
  IND: # Indirect mbufs
    capacity: 16383
    cachesize: 43
  ETHRX: # RX Ethernet frames
    capacity: 65535
    cachesize: 255
    dataroomsize: 8800
  NAME: # Name linearize
    capacity: 16383
    cachesize: 43
  HDR: # TX Ethernet+NDNLP+Interest headers
    capacity: 16383
    cachesize: 43
  INT: # TX Ethernet+NDNLP and encoding Interest
    capacity: 16383
    cachesize: 43
  DATA0: # TX Ethernet+NDNLP+Data name prefix
    capacity: 65535
    cachesize: 255
    dataroomsize: 9000
# FACE CREATION
face:
  enableeth: true     # Enable Ethernet faces
  ethmtu: 9000        # Ethernet device MTU
  ethrxqframes: 4096  # Ethernet RX queue capacity
  ethtxqpkts: 256     # Ethernet before-TX queue capacity
  ethtxqframes: 4096  # Ethernet after-TX queue capacity
  enablesock: false   # Enable socket faces
