# NDN-DPDK initialization configuration
---

# MEMORY POOL
# 'Capacity' affects the hugepage memory usage. 2^q-1 is optimal.
# Each NUMA socket has its own mempool with the given name.
Mempool:
  DIRECT:  # RX incoming packets
    Capacity: 524287
    Dataroom: 9000
  INDIRECT:  # indirect mbufs
    Capacity: 1048575
  INTEREST:  # TX Interests
    Capacity: 65535
  PAYLOAD:  # TX Data payload
    Capacity: 65535

# LCORE ALLOCATION
# This is a mapping from LCore role to its reservations.
# Roles for xrdndndpdk-consumer: RX, TX, ConsumerRx, ConsumerTx
# Roles for xrdndndpdk-producer: RX, TX, ProducerRx
# Within each role:
#  - 'LCores' is a list of lcores reserved for that role.
#  - 'OnNuma' is a map of { NUMA socket => max number of lcores } for that role.
#  - 'EachNuma' is max number of lcores per NUMA socket for that role.
# Leaving this section blank results in automatic allocation.
LCoreAlloc:
# ROLE1: # this role can use lcore 1 and lcore 3
#   LCores: [1, 3]
# ROLE2: # this role can have up to 3 and 2 lcores on two NUMA sockets
#   PerNuma:
#     0: 3
#     1: 2
# ROLE3: # this role can have up to 3 lcores on each NUMA socket
#   EachNuma: 3

# FACE CREATION
Face:
  # Whether to enable Ethernet faces.
  EnableEth: true
  # Whether to disable RxFlow dispatching.
  EthDisableRxFlow: false
  # Ethernet device MTU.
  EthMtu: 9000
  # RX queue capacity for Ethernet faces.
  EthRxqFrames: 4096
  # Before-TX queue capacity for Ethernet faces.
  EthTxqPkts: 256
  # After-TX queue capacity for Ethernet faces.
  EthTxqFrames: 4096

  # Whether to enable socket faces.
  EnableSock: true
  # RX queue capacity shared among all socket faces.
  SockRxqFrames: 4096
  # Before-TX queue capacity for socket faces.
  SockTxqPkts: 256
  # After-TX queue capacity for socket faces.
  SockTxqFrames: 1024
